### PR TITLE
Make it an object (fixes #5)

### LINKED ISSUE #5: what is `s`?
I see a bunch of functions using the variable `s`, well I don't see it defined anywhere, what is `s`?? Does this mean every instance of the object shares the exact same state?

### PR DESCRIPTION
**Pull request by LoganDark**
Incorporates the `parent` method from #6 (sorry, referenced issue 4 accidentally before)

---

- change this to an object (you can now store selections for later and still operate on them)
- switch to tabs (reduces file size, allows people to choose their indent size without affecting others, only uses one character per level, spaces can be used for alignment)
- add `sel` method for getting the now-scoped selection as a regular array of nodes
- **Breaking change:** `offset()` now returns the offset of the first element rather than setting a global variable to the offset of the last
- `getAttr()` now works, it returns the attribute gotten from the first element rather than being a no-op
- thanks to the fact that the selection is now an Array, the minified file can now use `forEach` because it's shorter than the `for` loops, but the downside is that you can't use automated minification anymore

This does not use proper classes with prototypes and things, because I was lazy. This is better than what the library was previously in any case. Let me know if you'd like me to revert any of these changes. This is completely untested though, so merge at your own risk

Note, this does not update the `lib` directory

### CODE REVIEW

**Comment by LoganDark** [comment]
Fixes #5 (GitHub does not register the reference in the title for some reason)

**Comment by vladocar** [comment]
Does it support chaining? 

Example: $("div").css("background-color:green;").html("Hello World")

**Comment by LoganDark** [comment]
The methods that don't return a value support chaining, yes. Methods with `return this` in the code allow you to chain afterwards since they return the same object the method was called on.

In any object, `obj.x()` calls `x()` with `obj` as the `this`.

**Comment by LoganDark** [comment]
I should remind you that this code is entirely untested.

**Comment by vladocar** [comment]
Try to test this with your code: $("div").css("background-color:green;").html("Hello World");

**Comment by LoganDark** [comment]
I was half-expecting you to test it for me since you're the maintainer and you know what's best, but sure, I'll try that.

**Comment by vladocar** [comment]
I just did :)

**Comment by LoganDark** [comment]
image
I think it works.

**Comment by vladocar** [comment]
Yes the css will work, what about html? Every div should display: "Hello World".

**Comment by LoganDark** [comment]
Good point. I'll look into it

**Comment by LoganDark** [comment]
So it turns out arrow functions preserve the `this` of the function they were defined in. That's fine, I'll use regular anonymous functions. Commits incoming.

**Comment by LoganDark** [comment]
image
On GitHub the new version produces the expected result.

**Comment by LoganDark** [comment]
Okay, I made a few updates. I made chaining work and added more argument types. You can now do stuff like

```
$(<HTMLElement of your choice>)
$(<Array of selectors>)
$(<Array of HTMLElements>)
$(<Array of any other argument the function accepts, including more arrays>)
```

Yay

**Comment by vladocar** [comment]
Ok.. I hope the result is different from my previous project https://github.com/vladocar/nanoJS/blob/master/src/nanoJS.js :)

**Comment by LoganDark** [comment]
Yep, it is, don't worry :) I'd love to become a maintainer here if that's possible!

I tested both the minified and non-minified versions of my latest commit and they both work.

**Comment by vladocar** [comment]
Ok, much better 👍 

Now I need to rewrite the docs and I will approve it..

**Comment by LoganDark** [comment]
You won't have to rewrite them fully, I hope.

**Comment by LoganDark** [comment]
I could rewrite them for you if you like. Where are they stored? I could add them to the PR

Edit: Nevermind, they're on a different branch. It's identical here though. I could add the latest commit from `gh-pages` to `master`, do this thing and then you could merge it back into `gh-pages`?

**Comment by vladocar** [comment]
Unfortunately I do. All in the interest of not polluting the global object.

**Comment by LoganDark** [comment]
Do you have any IM like Discord? This PR is getting loooong

**Comment by vladocar** [comment]
Yeah you are right. Just Skype..  I hope to finish with the docs today.

**Comment by LoganDark** [comment]
Make a [Gitter](https://gitter.im/) then?

**Comment by vladocar** [comment]
gitter.im/femtoJS

**Comment by LoganDark** [comment]
Did a bunch of stuff, maintainer approved, waiting on merge now

**Pull request merged**
